In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10, dtype='float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [5]:
a = np.arange(5)

In [6]:
type(a)

numpy.ndarray

In [7]:
a.size

5

In [9]:
a.max

<function max>

In [10]:
a.max()

4

In [11]:
a

array([0, 1, 2, 3, 4])

In [12]:
a.ndim

1

In [13]:
a.dtype

dtype('int32')

In [14]:
np.zeros((2,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
np.ones((4,3), dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [16]:
np.int16

numpy.int16

In [17]:
type(np.int16)

type

In [18]:
np.empty((5,5)) # output is random

array([[  1.96947215e-316,   2.86860127e-316,   1.96065288e-316,
          2.87000599e-316,   2.00771204e-316],
       [  2.86989374e-316,   1.96065288e-316,   2.87000836e-316,
          2.00771204e-316,   2.86814593e-316],
       [  1.96065288e-316,   2.87032220e-316,   2.00771204e-316,
          2.86998149e-316,   1.96065288e-316],
       [  2.86997200e-316,   2.00771204e-316,   2.86998386e-316,
          1.96065288e-316,   2.87002734e-316],
       [  2.00771204e-316,   3.75288668e-316,   1.96065288e-316,
          3.76068778e-316,   1.96947412e-316]])

In [20]:
np.arange(0, 2, 0.5)

array([ 0. ,  0.5,  1. ,  1.5])

There's no saying how many elements we'll actually get with the above due to floating pt precision issues

In [22]:
np.linspace(0, 2, 5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

The above is much more desired, since we specify (last arg) how many elements we want

In [23]:
np.pi

3.141592653589793

In [26]:
x = np.linspace(0, 2*np.pi, 11)

In [27]:
x

array([ 0.        ,  0.62831853,  1.25663706,  1.88495559,  2.51327412,
        3.14159265,  3.76991118,  4.39822972,  5.02654825,  5.65486678,
        6.28318531])

In [29]:
print(a)

[0 1 2 3 4]


In [30]:
print(x)

[ 0.          0.62831853  1.25663706  1.88495559  2.51327412  3.14159265
  3.76991118  4.39822972  5.02654825  5.65486678  6.28318531]


In [31]:
np.zeros(15, dtype=np.int16).reshape(3,5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)