In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [6]:
b = np.array([x*10 for x in range(1,5)])

In [7]:
a

array([0, 1, 2, 3])

In [8]:
b

array([10, 20, 30, 40])

Element wise operations (arithmetic)

In [9]:
c = a + b

In [10]:
c

array([10, 21, 32, 43])

In [11]:
b ** 2

array([ 100,  400,  900, 1600])

In [12]:
a ** 2

array([0, 1, 4, 9])

In [14]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001])

In [15]:
10 * np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008])

In [16]:
b < 32

array([ True,  True,  True, False], dtype=bool)

Not the "*" operator did not do a matrix multiplication

In [17]:
x = np.arange(6).reshape(2,3)

In [18]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
y = np.arange(9).reshape(3,3)

In [23]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
x.dot(y) # Matrix multiplication

array([[15, 18, 21],
       [42, 54, 66]])

In [27]:
A = np.ones((3,3), dtype=np.int)

In [28]:
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
A += 3

In [30]:
A

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [31]:
z = x.dot(y)

In [32]:
z.sum()

216

In [33]:
z.sum(axis=1)

array([ 54, 162])

In [35]:
z.sum(axis=0)

array([57, 72, 87])

In [39]:
k = np.random.random((4,5))
k *= 100

In [40]:
k

array([[ 53.39384272,  54.44302981,  92.65095713,  70.29928187,
          7.19883209],
       [ 80.9963818 ,  88.1407968 ,  64.77682916,  77.38354692,
         42.32769347],
       [ 81.14397258,  78.65988191,  85.38416313,  35.50209572,
         40.85136821],
       [ 22.23662394,  98.95179288,   6.46837254,  31.31398313,
         77.50493146]])

In [41]:
k.min(axis=0)

array([ 22.23662394,  54.44302981,   6.46837254,  31.31398313,   7.19883209])

In [42]:
k.min(axis=1)

array([  7.19883209,  42.32769347,  35.50209572,   6.46837254])